### PR TITLE
Add @ShogunPanda to attendees

### PR DESCRIPTION
**Pull request by ShogunPanda**

### CODE REVIEW

**Comment by benjie** [comment]
@ShogunPanda Are you able to get the CLA in place in order to join the meeting?

**Comment by ShogunPanda** [comment]
@benjie Sorry, I had limited coverage. Doing it now.

**Comment by ShogunPanda** [comment]
@benjie Apparently our CLA manager is not working today. Can I join the meeting and get this sorted tomorrow?

**Comment by benjie** [comment]
I'm really sorry @ShogunPanda but that's against policy - everyone attending must have agreed. You could sign it as an individual contributor though, that's what I did years ago :)

If you can't make it, the video will be put up on YouTube before the next meeting so you should be able to catch up - we also take copious notes: https://github.com/graphql/composite-schemas-wg/blob/main/notes/2022/2022-07-14.md

**Comment by ShogunPanda** [comment]
I'll sign as individual then for now not to lose the meeting. Doing it right now!

**Comment by ShogunPanda** [comment]
@benjie Done, much much easier! XD

**Pull request merged**
